name: Web app
on:
  push:
    branches:
      - ui-update

concurrency:
  group: web-app-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_web_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm compile:web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        #if: ${{ github.ref_name == 'main' }}
        # Hack - temporarily have this branch take over orbiter.riff.cc publishing
        if: ${{ github.ref_name == 'ui-update' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/renderer/dist/web
          cname: orbiter.riff.cc
