name: Web app tests
on: [ workflow_call ]

concurrency:
  group: web-app-tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  tests_navig:
    strategy:
      fail-fast: false
      matrix:
        navig: [ firefox, chromium ] #  , webkit ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - run: pnpm install

      - run: pnpm exec playwright install

      - run: pnpm test:webkit
        if: ${{ matrix.navig == 'webkit' }}

      - run: pnpm test:chrome
        if: ${{ matrix.navig == 'chromium' }}

      - run: pnpm test:firefox
        if: ${{ matrix.navig == 'firefox' }}

      # Publish coverage to CodeCov
      - name: Send to Codecov
        uses: codecov/codecov-action@v4
